# FILEPATH: .circleci/config.yml
version: 2.1
jobs:
  build-docker-image-push:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: 
          name: Docker login 
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t mlvault/runpod-code-server:$CIRCLE_TAG --progress=plain .
      - run:
          name: Push Docker image
          command: docker push mlvault/runpod-code-server:$CIRCLE_TAG
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-docker-image-push:
          context: dockerhub
          filters:
            tags:
              only: /v.*/
            branches:
              only:
                - main